### ISSUE TITLE
simpler carrying - suggestion

### ISSUE THREAD

**Issue by superon** [GabrielOlvH/Carrier#13]
could se have it so players can carry/place simply by pushing the chosen keybind rather than having, as it is now, the need to push the keybind AND mouse right click?
this way players will be able to carry entities otherwise inaccessible due to having a right-click action, such as horses, traders and villagers.   seems we CAN carry chests that would otherwise open on right-click so maybe inconsistent.

**Comment by GabrielOlvH** [comment]
Horses, traders, villagers and plenty of other entities aren't carriable by my choice (as it would be incredibly op), not because it uses right click to pick stuff up. The keybinding + right click won't be changed

**Comment by superon** [comment]
i'd rather have thought it op by choice, carrier does have the option to blacklist if someone deems them to be so within the config so i feel it's more down to how a pack is built as to whether it's op or not.   feels it's better to have the option though so be it.  thanks for responding
