### ISSUE TITLE
[Bug] Duplication bug for two block height blocks

### ISSUE THREAD

**Issue by mrsolarius** [GabrielOlvH/Carrier#23]
### Describe the bug
When you carry a block with height of two blocks, and you place it. When you break the block that is jute placed, you get item twice and the duplication bug append.

### To Reproduce
1. Take a two blocks height item
2. Place it
3. Break this item
4. See the beautiful duplication bug

### Expected behavior
I expect that the block is correctly placed, and the item is not duplicate

### Explains video
This video explains the problem : https://www.youtube.com/watch?v=NCEdqRC3A5o

### Environment
- Minecraft: 1.17.0
- Fabric Loader: 0.11.6
- Fabric API: 0.36.0+1.17

### Additional context

I have found this bug with the famous mode pack that use your mode : [Better Minecraft](https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric)

**Comment by GabrielOlvH** [comment]
This looks like an issue with how Waystones handle their blocks. This for example doesn't happen with Minecraft beds or Industrial Revolution's Mining Rig Drills.
