### ISSUE TITLE
[Bug] Game will not open after deleting mod

### ISSUE THREAD

**Issue by Histarium** [GabrielOlvH/Carrier#24]
I needed to delete the mod for the time being due to an incompatibility with Dank Storage (It deleted all my items out of A Storage unit because they share hotkeys) and after doing so I no longer can open minecraft. Once I put it back into the mod folder, it will launch minecraft like normal again. 

Crash Report After Removing Mod From Mods Folder: 
[crash-2021-08-13_23.41.03-client.txt](https://github.com/GabrielOlvH/Carrier/files/6985895/crash-2021-08-13_23.41.03-client.txt)

**Comment by red2blue** [comment]
Cough logs.
