### ISSUE TITLE
[Feature Request] Several implementation ideas

### ISSUE THREAD

**Issue by Abbanon** [GabrielOlvH/Carrier#3]
So I've got several requests/ideas that this mod could really make use of:
- ModMenu support for configuration
- Toggle to disable slowness, *and* configurable slowness
- Toggle to disable increased hunger, *and* configurable increased hunger
- Configurable hotkey in Options > Controls (for people who don't want Shift+RightClick)

**Comment by GabrielOlvH** [comment]
I've implemented configurable slowness and hunger (just set 0 to disable) alongside a bugfix in 1.4.0 since these were the easiest one to do, I'll do the other ones for a future update. Thanks for the suggestions!

**Comment by GabrielOlvH** [comment]
Pretty much everything was implemented except mod menu support which is not really something I want to add for now so I'll be closing this
