### ISSUE TITLE
Support Regex in Whitelist/blacklist

### ISSUE THREAD

**Issue by itsdinkd** [GabrielOlvH/Carrier#37]
Please. Support regex... or at least wildcards... its very time consuming to write down a list of blocks you want to whitelist when you have a modpack with 298 mods.

**Comment by GabrielOlvH** [comment]
It already supports it 😉

**Comment by itsdinkd** [comment]
Uhhh... hm.. I've had my blacklist initially using regex and it definitely did not support it. Though I used basic wildcards like *
