### ISSUE TITLE
Can't pick up all mobs?

### ISSUE THREAD

**Issue by the-potatocouch** [GabrielOlvH/Carrier#38]

**Comment by the-potatocouch** [comment]
I set my config file to this:
```json
{
  "enableGloves": false,
  "slownessLevel": 0,
  "hungerExhaustion": 0,
  "type": "BLACKLIST",
  "list": []
}
```

**Comment by the-potatocouch** [comment]
if there is nothing in the blacklist, wouldn't that mean that every mob is allowed? However, I cannot pick them all up.

**Comment by GabrielOlvH** [comment]
Carrier doesn't yet suport carrying every mob, this is being worked on, it's not an issue.
