### ISSUE TITLE
Bug: Modded chests get transformed to vanilla chest after placement

### ISSUE THREAD

**Issue by Xetheon** [GabrielOlvH/Carrier#6]
The title says it all really. Any items inside a modded chest remain just fine after placing it back down, however, the chest itself becomes a normal vanilla chest. This seems to happen with any modded chest at all

**Comment by GabrielOlvH** [comment]
Fixed as of 1.6.1 which you can download [here](https://www.curseforge.com/minecraft/mc-mods/carrier/files/3127555)
