### ISSUE TITLE
1.16.4 Fabric - Server Crashes when adding Carrier

### ISSUE THREAD

**Issue by panaretos** [GabrielOlvH/Carrier#7]
Server crashes adding Carrier mod.  Attached is crashlog
[crash-2020-12-26_07.01.57-server.txt](https://github.com/GabrielOlvH/Carrier/files/5743111/crash-2020-12-26_07.01.57-server.txt)

**Comment by GabrielOlvH** [comment]
Can you reproduce this with just Carrier? Seems to be crashing with WorldEdit, I'll look into this. Thanks for the report.

**Comment by ndrp** [comment]
Hi, I also get a server crash caused at least in part by Carrier. Removing Carrier fixes the crash. Interestingly there are no problems in singleplayer or LAN environment. Unfortunately I don't know much about Fabric or Mixins yet, so I couldn't make much more of the crash log except figuring out that Carrier has something to do with it. Possibly conflicting with another mod? But then again it's weird that it works in singleplayer. https://pastebin.com/m1PEfeCf

**Comment by GabrielOlvH** [comment]
Should not be an issue anymore, thanks for the report.
